spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/toy-project2
    username: root
    password: 1234
  jpa:
    hibernate:
      show-sql: true
      ddl-auto: create
      jdbc:
        time_zone: Asia/Seoul
